definitions:
  steps:
    publishToArtifactory: &publishToArtifactory
      image: "atlassian/default-image:5"
      size: 4x
      runtime:
        cloud:
          instance-type: "standard"
      name: Publish To Artifactory
      script:
        - pipe: docker://atlassian/artifactory-sidekick:latest
        - source .artifactory/activate.sh
        - cd java
        - apt update -y
        - apt install -y openjdk-11-jdk git gcc pkg-config openssl libssl-dev unzip cmake
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        - ./gradlew publish
    build: &build
      image: "atlassian/default-image:5"
      size: 4x
      runtime:
        cloud:
          instance-type: "standard"
      name: Build
      script:
        - pipe: docker://atlassian/artifactory-sidekick:latest
        - source .artifactory/activate.sh
        - cd java
        - apt update -y
        - apt install -y openjdk-11-jdk git gcc pkg-config openssl libssl-dev unzip cmake
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        - ./gradlew build
pipelines:
  default:
    - step: *build
  custom:
    manual-publish-to-artifactory:
      - step: *publishToArtifactory
  pull-requests:
    main:
      - step: *build
  branches:
    main:
      - step: *publishToArtifactory
